// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0F_8TwjCISthoxW-c_H9VCpf0Q9CoXKw',
    appId: '1:76177554502:web:fe6cbdd4658c4fe3165e47',
    messagingSenderId: '76177554502',
    projectId: 'kpi-project-37e47',
    authDomain: 'kpi-project-37e47.firebaseapp.com',
    storageBucket: 'kpi-project-37e47.firebasestorage.app',
    measurementId: 'G-KKXGK7P2Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDelUqavI-iK3wpCZ6s367ETJO8Km-K0mI',
    appId: '1:76177554502:android:e84667f5e196a93f165e47',
    messagingSenderId: '76177554502',
    projectId: 'kpi-project-37e47',
    storageBucket: 'kpi-project-37e47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbXgEoFvanmXTbDz_xzkF4PGot2iG4-8U',
    appId: '1:76177554502:ios:43b1891d836f5af9165e47',
    messagingSenderId: '76177554502',
    projectId: 'kpi-project-37e47',
    storageBucket: 'kpi-project-37e47.firebasestorage.app',
    iosBundleId: 'com.example.telescopePhoneV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbXgEoFvanmXTbDz_xzkF4PGot2iG4-8U',
    appId: '1:76177554502:ios:43b1891d836f5af9165e47',
    messagingSenderId: '76177554502',
    projectId: 'kpi-project-37e47',
    storageBucket: 'kpi-project-37e47.firebasestorage.app',
    iosBundleId: 'com.example.telescopePhoneV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0F_8TwjCISthoxW-c_H9VCpf0Q9CoXKw',
    appId: '1:76177554502:web:ca886cf6b09fc42f165e47',
    messagingSenderId: '76177554502',
    projectId: 'kpi-project-37e47',
    authDomain: 'kpi-project-37e47.firebaseapp.com',
    storageBucket: 'kpi-project-37e47.firebasestorage.app',
    measurementId: 'G-YK0FQEKTH0',
  );

}